title: ludingze's Homepage
page-top-title: Ludingze
top-section-bg-text: Be what you wanna be
home-subtitle: Ludingze&ensp;|&ensp;卢定泽
copyright-text: '&copy; Ludingze 2024-2026. All Rights Reserved.'
